name       : haskell-generics-sop
version    : 0.3.2.0
release    : 4
source     :
    - https://hackage.haskell.org/package/generics-sop-0.3.2.0/generics-sop-0.3.2.0.tar.gz : 3060ecd09ccbd27ecf825bb89af0af9cfcadd16f747ce5964c501682a2301b99
license    : BSD-3-Clause
component  : programming.haskell
summary    : A library to support the definition of generic functions.
description: |
    A library to support the definition of generic functions. Datatypes are viewed in a uniform, structured way: the choice between constructors is represented using an n-ary sum, and the arguments of each constructor are represented using an n-ary product.
builddeps  :
    - ghc-devel
    - haskell-cabal-install
rundeps    :
    - devel:
        - ghc-devel
networking : yes
setup      : |
    sed -i "s|2.14|2.15|g" *.cabal
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
